### ISSUE TITLE
Cannot use Edge as PDF Viewer

### ISSUE THREAD

**Issue by skyfighteer** [valnoxy/GoAwayEdge#19]
Hi!! Love your program. But the only thing I use edge for is to view PDF files. However, I think your utility breaks it. When I try to open the pdf, nothing happens. Thanks in advance ;)

**Comment by valnoxy** [comment]
thanks for your feedback. this should be fixed now.

**Comment by skyfighteer** [comment]
Hi!
Thanks for the fix. However, I think the new parser broke something, because now the edge opens, but the link is "separated" into different tabs.
The file location is "C:\Users\W10_TEST_BIOS\OneDrive - Széchenyi István Egyetem\Desktop\a.pdf". And this link gets opened in 5 different tabs.
1. "file:///C:/Users/W10_TEST_BIOS/OneDrive/"
2. "-"
3. "széchenyi/"
4. "istván/"
5. "egyetem/Desktop/a.pdf"

**Comment by valnoxy** [comment]
Thanks for the info. Could you check if the bug is still present in this version?
[GoAwayEdge_v1.3.2.141_net8.0-windows10.0.18362.0.zip](https://github.com/user-attachments/files/15568849/GoAwayEdge_v1.3.2.141_net8.0-windows10.0.18362.0.zip)

**Comment by skyfighteer** [comment]
Yes sir, perfect. Thank you very much! Keep up the great work.
