### ISSUE TITLE
Constantly opens every startup

### ISSUE THREAD

**Issue by Thespikedballofdoom** [valnoxy/GoAwayEdge#24]
It's even worse recently because installing it now has to go through the entire installation process.

**Comment by HuxyDane** [comment]
Yep. Is there any way to disable the update reminder? It's more annoying then Edge problem itself

**Comment by valnoxy** [comment]
thanks for your feedback, i will look into that.

To prevent the update notification from appearing when starting, disable the task ```valnoxy\GoAwayEdge\GoAwayEdge Validation & Update Task``` in the task scheduler.

**Comment by valnoxy** [comment]
Does the bug still exist in this version?
[GoAwayEdge_v1.3.3.150_net8.0-windows10.0.18362.0.zip](https://github.com/user-attachments/files/15753871/GoAwayEdge_v1.3.3.150_net8.0-windows10.0.18362.0.zip)

**Comment by Thespikedballofdoom** [comment]
It does seem to avoid the issue yeah

**Comment by HuxyDane** [comment]
> Yep. Is there any way to disable the update reminder? It's more annoying then Edge problem itself

Sorry if my comment seemed toxic, I must have been in a bad mood. This is a very useful app, thank you!

**Comment by Thespikedballofdoom** [comment]
It's not every startup, but it's still showing up randomly.

**Comment by Thespikedballofdoom** [comment]
Still happening

**Comment by valnoxy** [comment]
> Still happening

Sorry for the late response. Does the app update popup appear or the one regarding the alternative startup file update? Which version do you currently have installed?

**Comment by Thespikedballofdoom** [comment]
Having uninstalled and reinstalled, it hasnt happened for 2 installs in a row. It said it was on the same version i have installed this time while i was bugging, so maybe something wasn't cleared last time or something. But it is fixed after reinstalling the newest version
