### ISSUE TITLE
Copilot not working on Windows 11 Preview 

### ISSUE THREAD

**Issue by Haris00911** [valnoxy/GoAwayEdge#28]
### What happened?

Copilot will not open if GoAwayEdge is installed, tried to use hotkey and manually opening Copilot but nothing happens.

### Channel

Stable (default)

### Search Engine

Google

### How to reproduce

Windows 11 Preview Build 26241
Edge Version 127.0.2651.31 

### Additional information

2024-07-03 21:50:07 - INFO - GoAwayEdge 1.3.3 (Build 150)
2024-07-03 21:50:07 - INFO - Logging system initialized
2024-07-03 21:50:07 - INFO - Trying to load language: en-US
2024-07-03 21:50:12 - INFO - Start installation ...
2024-07-03 21:50:12 - ERROR - Failed to delete old task: System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.DeleteTask(String Name, Int32 flags)
   at Microsoft.Win32.TaskScheduler.TaskFolder.DeleteTask(String name, Boolean exceptionOnNotExists)
   at GoAwayEdge.Common.InstallRoutine.Install(Object sender, DoWorkEventArgs e)
2024-07-03 21:50:12 - INFO - Installation finished.

**Comment by valnoxy** [comment]
Sorry for the late response. I could not reproduce the problem in the latest Insider Preview. It is possible that the alternative startup file is outdated / corrupted. 

Try the following:

1. Open Command Prompt (not as administrator) and type: ```"C:\Program Files\valnoxy\GoAwayEdge\GoAwayEdge.exe" --update```
2. If the alternative start file is outdated or corrupt, a window will appear asking you to update it. Confirm this with "Yes".

Should it still not work, delete the following file and repeat the above steps: ```C:\Program Files (x86)\Microsoft\Edge\Application\msedge_non_ifeo.exe```

**Comment by Haris00911** [comment]
No problem, I meant to get back to you sooner too. Unfortunately the steps you shared didn't work for me. The command by itself didn't do anything and after deleting the exe and running the command again, the prompt to confirm yes appeared but still no change in CoPilot working. Here's a screen recording of the steps I tried. 
[GoAwayEdge Issue.webm](https://github.com/user-attachments/assets/93c6d28a-2e3a-49b7-b3e6-ba884ae4a6df)

**Comment by valnoxy** [comment]
Ah, I see the issue. You are using the PWA app from Copilot. I had fixed the bug [in the dev branch](https://github.com/valnoxy/GoAwayEdge/commit/14d0d8704441b4c66d99fbec2f6ee75b49e96496) the other day. Here is a current build: 
[GoAwayEdge_v1.3.4.153_14d0d8704441b4c66d99fbec2f6ee75b49e96496_signed.zip](https://github.com/user-attachments/files/16416270/GoAwayEdge_v1.3.4.153_14d0d8704441b4c66d99fbec2f6ee75b49e96496_signed.zip)

**Comment by Haris00911** [comment]
Works like a charm! Thank you, appreciate the help:
