### ISSUE TITLE
GoAwayEdge Sometimes 

### ISSUE THREAD

**Issue by radische** [valnoxy/GoAwayEdge#3]

**Comment by radische** [comment]
When GoAwayEdge 1.0.1 is running and I attempt to access my Overflow Shortcuts on my Windows 11 Pro 22621.819 Taskbar, it cannot be opened until I "uninstall" GoAwayEdge.

**Comment by valnoxy** [comment]
Hello, thank you for your feedback and sorry for the late reply. I'm not sure what you mean by "overflow shortcuts", can you tell me more about it?
